import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import { LayoutMain } from '@/layouts/LayoutMain';
import { BoxEars } from '@/shared/ui/BoxEars';
import { Header } from '@/widgets/Header';

export const metadata: Metadata = {
  title: 'Markar test app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <LayoutMain>
            <BoxEars>
              <Header />
              {children}
            </BoxEars>
          </LayoutMain>
        </Providers>
      </body>
    </html>
  );
}
